version: "3"

vars:
  ENTRY: "{{.ENTRY}}"
  TARGET: '{{default "test" .TARGET}}'

tasks:
  yarn:
    internal: true
    cmds:
      - yarn run --silent {{.CMD}}
    vars:
      CMD: "{{.CMD}}"

  node:
    internal: true
    cmds:
      - node {{.CMD}}
    vars:
      CMD: "{{.CMD}}"

  #outDir:
  #  internal: true
  #  cmds:
  #    - outDir=$(node -e 'const conf = require("./tsconfig.{{.TARGET}}.json"); console.log(conf.compilerOptions.outDir);') && {{.OPER}}
  #  vars:
  #    OPER: "{{.OPER }}"

  build:
    cmds:
      #  - task: outDir
      #    vars:
      #      OPER: rm -rf "$outDir"
      #  - task: yarn
      #    vars:
      #      BIN: tsc --noEmit --project tsconfig.{{.TARGET}}.json
      - task: node
        vars:
          CMD: ./cli/build -t tsconfig.{{.TARGET}}.json

  test:
    cmds:
      - clear
      - task: build
      - task: node
        vars:
          CMD: ./cli/unitTest -p ./**/*{{default "*" .ENTRY}}*.spec.js
    sources:
      - src/**/*.ts
    generates:
      - ./build-test/**/*
    method: timestamp
