version: "3"

tasks:
  yarn:
    internal: true
    cmds:
      - yarn run --silent {{.BIN}}
    vars:
      BIN: "{{.BIN}}"

  cli:
    internal: true
    cmds:
      - node {{.SCRIPT}}
    vars:
      SCRIPT: "{{.SCRIPT}}"

  build:
    internal: true
    cmds:
      - outDir=$(node -e 'const a = require("./{{.TSCONFIG}}"); console.log(a.compilerOptions.outDir);') && rm -rf "$outDir"
      - tsc --noEmit --project {{.TSCONFIG}}
      - task: cli
        vars:
          SCRIPT: ./cli/build -t {{.TSCONFIG}}
    vars:
      TSCONFIG: tsconfig.{{.BUILD_TARGET}}.json

  build-test:
    internal: true
    cmds:
      - task: build
        vars:
          BUILD_TARGET: test

  test:
    cmds:
      - clear
      - task: build-test
      - task: cli
        vars:
          SCRIPT: ./cli/unitTest -p ./**/*{{.PATTERN}}*.spec.js
    vars:
      PATTERN: '{{default "*" .PATTERN}}'
    sources:
      - src/**/*.ts
    generates:
      - ./build-test/**/*
    method: timestamp
