version: "3"

vars:
  F: "{{.F}}"
  T: '{{default "test" .T}}'

tasks:
  yarn:
    internal: true
    cmds:
      - yarn run --silent {{.CMD}}
    vars:
      CMD: "{{.CMD}}"

  cli:
    internal: true
    cmds:
      - node {{.CMD}}
    vars:
      CMD: "{{.CMD}}"

  outDir:
    internal: true
    cmds:
      - outDir=$(node -e 'const conf = require("./tsconfig.default.json"); console.log(conf.compilerOptions.outDir);') && {{.CMD}}
    vars:
      CMD: "{{.CMD }}"

  build:
    internal: true
    deps:
      - task: outDir
        vars:
          CMD: rm -rf "$outDir"
      - task: yarn
        vars:
          CMD: tsc --noEmit --project tsconfig.{{.T}}.json
    cmds:
      - task: cli
        vars:
          CMD: ./cli/build -t tsconfig.{{.T}}.json -p {{.PLATFORM}}
    vars:
      T: "{{.T}}"
      PLATFORM: "{{.PLATFORM}}"

  declare:
    internal: true
    cmds:
      - task: yarn
        vars:
          CMD: tsc --emitDeclarationOnly --project tsconfig.{{.T}}.json
      - task: yarn
        vars:
          CMD: tsc-alias -p tsconfig.{{.T}}.json

  dist:
    deps:
      - task: build
        vars:
          PLATFORM: browser
      - task: declare
    cmds:
      - echo 'export * from "./entries/{{.F}}"' > ./dist/index.js
      - echo 'export * from "./entries/{{.F}}"' > ./dist/index.d.ts
    sources:
      - src/**/*.ts
    generates:
      - ./dist/**/*
    method: timestamp

  test:
    cmds:
      - clear
      - task: build
        vars:
          T: testset
          PLATFORM: node
      - task: cli
        vars:
          CMD: ./cli/unitTest -p ./**/*{{default "*" .F}}*.spec.js
    sources:
      - src/**/*.ts
    generates:
      - ./dist/**/*
    method: timestamp
