version: "3"

tasks:
  yarn:
    internal: true
    cmds:
      - yarn run --silent {{.BIN}}
    vars:
      BIN: "{{.BIN}}"

  build:
    internal: true
    cmds:
      - outDir=$(node -e 'const a = require("./{{.TSCONFIG}}"); console.log(a.compilerOptions.outDir);') && rm -rf "$outDir"
      - task: yarn
        vars:
          BIN: tsc --project {{.TSCONFIG}}
      - task: yarn
        vars:
          BIN: tsc-alias -p {{.TSCONFIG}}
    vars:
      TSCONFIG: tsconfig.{{.BUILD_TARGET}}.json

  build-test:
    internal: true
    cmds:
      - task: build
        vars:
          BUILD_TARGET: test

  test:
    cmds:
      - clear
      - task: build-test
      - yarn --silent ava ./**/*{{.PATTERN}}*.spec.js
    vars:
      PATTERN: '{{default "*" .PATTERN}}'
    sources:
      - src/**/*.ts
    generates:
      - ./build-test/**/*
    method: timestamp
