version: "3"

vars:
  E: "{{.E}}"
  T: '{{default "test" .T}}'

tasks:
  yarn:
    internal: true
    cmds:
      - yarn run --silent {{.CMD}}
    vars:
      CMD: "{{.CMD}}"

  cli:
    internal: true
    cmds:
      - node {{.CMD}}
    vars:
      CMD: "{{.CMD}}"

  outDir:
    internal: true
    cmds:
      - outDir=$(node -e 'const conf = require("./tsconfig.default.json"); console.log(conf.compilerOptions.outDir);') && {{.CMD}}
    vars:
      CMD: "{{.CMD }}"

  build:
    cmds:
      - task: outDir
        vars:
          CMD: rm -rf "$outDir"
      - task: yarn
        vars:
          CMD: tsc --noEmit --project tsconfig.{{.T}}.json
      - task: cli
        vars:
          CMD: ./cli/build -t tsconfig.{{.T}}.json
    vars:
      T: "{{.T}}"

  #declare:
  #  cmds:
  #    - tsc --emitDeclarationOnly --project tsconfig.{{.T}}.json

  #test:
  #  cmds:
  #    - clear
  #    - task: build
  #      vars:
  #        T: testset
  #    - task: cli
  #      vars:
  #        CMD: ./cli/unitTest -p ./**/*{{default "*" .E}}*.spec.js
  #  sources:
  #    - src/**/*.ts
  #  generates:
  #    - ./build-test/**/*
  #  method: timestamp
